<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/config.php';
if (!is_authenticated() || !is_teacher()) { redirect_to('/'); exit; }
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Revision de Propuestas - <?= APP_NAME ?></title><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/visual-preferences.php'; ?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css"><link rel="stylesheet" href="/assets/css/app.css"></head>
<body><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/navbar.php'; ?><div class="d-flex content-wrapper"><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/sidebar.php'; ?><main class="main-content flex-grow-1"><div class="container-xl mt-5 mb-5"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="mb-0">Revision de Propuestas</h1><button class="btn btn-primary" onclick="loadProjects()"><i class="bi bi-arrow-clockwise"></i></button></div><div id="projectsContainer" class="row g-4"></div></div></main></div><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>const API_BASE_URL='<?= API_BASE_URL ?>';</script><script src="/assets/js/auth.js"></script><script src="/assets/js/api.js"></script>
<script>
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badge=s=>({pendiente:'bg-warning text-dark',aprobado:'bg-success',requiere_cambios:'bg-info text-dark',rechazado:'bg-danger'}[s]||'bg-secondary');
const fullName=u=>[u?.nombres,u?.apa,u?.ama].filter(Boolean).join(' ')||u?.id||'';
const activeAuthors=p=>(Array.isArray(p?.students)?p.students:[]).map(fullName).filter(Boolean).join(', ')||'-';
async function loadProjects(){const projects=await api.get('/proposal/teacher-projects');const box=document.getElementById('projectsContainer');if(!projects.length){box.innerHTML='<p class="text-muted">No tienes grupos de revision asignados.</p>';return;}box.innerHTML=projects.map(p=>`<div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-start"><h5>${esc(p.title)}</h5><span class="badge ${badge(p.proposal_status)}">${esc(p.proposal_status)}</span></div><p class="text-muted">${esc(p.description||'Sin descripcion')}</p><small class="d-block"><i class="bi bi-people"></i> ${esc(activeAuthors(p))}</small><small class="d-block"><i class="bi bi-collection"></i> ${esc(p.subject_group?.nombre||'-')}</small><hr><strong>Empresa</strong><p class="mb-1">${esc(p.company_name||'-')}</p><small>${esc(p.company_contact_name||'')} ${esc(p.company_contact_position||'')}</small>${p.proposal_review_comment?`<div class="alert alert-light border mt-3 mb-0">${esc(p.proposal_review_comment)}</div>`:''}</div><div class="card-footer bg-light border-0 d-flex gap-2"><button class="btn btn-sm btn-success" onclick="review(${p.id},'aprobado')">Aprobar</button><button class="btn btn-sm btn-warning" onclick="review(${p.id},'requiere_cambios')">Correcciones</button><button class="btn btn-sm btn-danger" onclick="review(${p.id},'rechazado')">Rechazar</button></div></div></div>`).join('');}
async function review(id,status){let comment='',until=null;const c=await Swal.fire({title:'Comentario',input:'textarea',inputPlaceholder:'Observaciones para el alumno',showCancelButton:true,confirmButtonText:'Continuar'});if(!c.isConfirmed)return;comment=c.value||'';if(status==='requiere_cambios'){const d=await Swal.fire({title:'Permitir correccion hasta',input:'datetime-local',showCancelButton:true,confirmButtonText:'Guardar'});if(!d.isConfirmed||!d.value)return;until=d.value;}try{await api.post(`/proposal/projects/${id}/review`,{proposal_status:status,proposal_review_comment:comment,revision_allowed_until:until});swalToast('Revision registrada','success');loadProjects();}catch(e){Swal.fire('Error',e.message,'error');}}
document.addEventListener('DOMContentLoaded',loadProjects);
</script></body></html>
