<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/config.php';
if (!is_authenticated() || !is_student()) { redirect_to('/'); exit; }
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Registro de Proyecto - <?= APP_NAME ?></title><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/visual-preferences.php'; ?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css"><link rel="stylesheet" href="/assets/css/app.css"></head>
<body><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/navbar.php'; ?><div class="d-flex content-wrapper"><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/sidebar.php'; ?><main class="main-content flex-grow-1"><div class="container-xl mt-5 mb-5"><h1 class="mb-4">Registro de Proyecto</h1><div id="statusBox" class="mb-4"></div><div class="card border-0 shadow-sm" id="formCard" style="display:none"><form id="projectForm" class="card-body"><div class="row g-3"><div class="col-12"><label class="form-label">Nombre del proyecto</label><input class="form-control" name="title" required></div><div class="col-12"><label class="form-label">Descripcion</label><textarea class="form-control" name="description" rows="4" required></textarea></div><div class="col-md-6"><label class="form-label">Empresa o negocio</label><input class="form-control" name="company_name" required></div><div class="col-md-6"><label class="form-label">Giro</label><input class="form-control" name="company_giro" required></div><div class="col-md-6"><label class="form-label">Persona a cargo</label><input class="form-control" name="company_contact_name" required></div><div class="col-md-6"><label class="form-label">Puesto</label><input class="form-control" name="company_contact_position" required></div><div class="col-md-6"><label class="form-label">Direccion</label><input class="form-control" name="company_address" required><div class="form-text">Separa calle, numero, colonia y municipio con comas (,).</div></div><div class="col-md-8"><label class="form-label">Agregar integrante disponible</label><input class="form-control" id="studentSearch" list="studentsList" placeholder="Numero de control o nombre"><datalist id="studentsList"></datalist></div><div class="col-md-4 d-flex align-items-end"><button type="button" class="btn btn-outline-primary w-100" onclick="addSelectedStudent()"><i class="bi bi-person-plus"></i> Agregar</button></div><div class="col-12"><div id="selectedStudents" class="d-flex flex-wrap gap-2"></div></div></div><div class="text-end mt-4"><button class="btn btn-primary"><i class="bi bi-send"></i> Registrar propuesta</button></div></form></div></div></main></div><?php require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>const API_BASE_URL='<?= API_BASE_URL ?>';</script><script src="/assets/js/auth.js"></script><script src="/assets/js/api.js"></script>
<script>
let statusData=null, students=[], selected=[], editingProjectId=null; const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function renderSelected(){document.getElementById('selectedStudents').innerHTML=selected.map(s=>`<span class="badge bg-info text-dark">${esc(s.id)} - ${esc(s.nombres)} ${esc(s.apa||'')} <button type="button" class="btn btn-sm p-0 ms-1" onclick="selected=selected.filter(x=>x.id!=='${esc(s.id)}');renderSelected()"><i class="bi bi-x"></i></button></span>`).join('');}
async function loadStatus(){statusData=await api.get('/proposal/student-status');const box=document.getElementById('statusBox');if(statusData.profile_required){box.innerHTML='<div class="alert alert-warning">Debes completar tu perfil inicial antes de registrar un proyecto.</div>';return;}if(statusData.project){const p=statusData.project;const canEdit=p.proposal_status==='requiere_cambios'&&p.revision_allowed_until&&new Date(p.revision_allowed_until)>new Date();box.innerHTML=`<div class="alert ${canEdit?'alert-warning':'alert-info'}"><strong>Proyecto ligado:</strong> ${esc(p.title)}<br>Estado: <span class="badge bg-secondary">${esc(p.proposal_status)}</span>${p.revision_allowed_until?`<br>Correcciones hasta: ${new Date(p.revision_allowed_until).toLocaleString('es-MX')}`:''}${p.proposal_review_comment?`<br><strong>Observaciones:</strong> ${esc(p.proposal_review_comment)}`:''}</div>`;if(canEdit){editingProjectId=p.id;document.querySelector('[name="title"]').value=p.title||'';document.querySelector('[name="description"]').value=p.description||'';['company_name','company_contact_name','company_contact_position','company_address'].forEach(k=>document.querySelector(`[name="${k}"]`).value=p[k]||'');document.getElementById('formCard').style.display='';document.querySelector('#projectForm button[type="submit"]').innerHTML='<i class="bi bi-save"></i> Enviar correccion';document.getElementById('studentSearch').closest('.col-md-8').style.display='none';document.getElementById('studentSearch').closest('.col-md-8').nextElementSibling.style.display='none';}return;}if(!statusData.active_window){box.innerHTML='<div class="alert alert-secondary">El registro de proyectos no esta abierto para tu grupo.</div>';return;}box.innerHTML=`<div class="alert alert-success">Registro habilitado hasta ${new Date(statusData.active_window.ends_at).toLocaleString('es-MX')}</div>`;document.getElementById('formCard').style.display='';}
async function searchStudents(){const q=document.getElementById('studentSearch').value;if(q.length<2)return;students=await api.get('/proposal/students/search',{q});const selectedIds=selected.map(s=>String(s.id));document.getElementById('studentsList').innerHTML=students.filter(s=>!selectedIds.includes(String(s.id))).map(s=>`<option value="${esc(s.id)} - ${esc(s.nombres)} ${esc(s.apa||'')}"></option>`).join('');}
function addSelectedStudent(){const value=document.getElementById('studentSearch').value;const id=value.split(' - ')[0].trim();const s=students.find(x=>x.id===id);if(!s||selected.some(x=>x.id===s.id))return;selected.push(s);renderSelected();document.getElementById('studentSearch').value='';document.getElementById('studentsList').innerHTML='';}
document.getElementById('studentSearch').addEventListener('input',searchStudents);
document.getElementById('projectForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());try{if(editingProjectId){await api.put(`/projects/${editingProjectId}`,data);swalToast('Correccion enviada','success');}else{data.subject_group_id=statusData.subject_group.id;data.student_ids=selected.map(s=>s.id);await api.post('/projects',data);swalToast('Proyecto registrado','success');}setTimeout(()=>location.reload(),900);}catch(err){Swal.fire('Error',err.message,'error');}});
document.addEventListener('DOMContentLoaded',loadStatus);
</script></body></html>
